[package]
name = "kj_light"
version = "0.1.0"
authors = ["Vladimir Kochnev <kijemori@gmail.com>"]
description = "Ultra-fast SDF-based GUI and 3D interaction library. < 2.5ms frame time."
license = "AGPL-3.0-only"
edition = "2024"
repository = "https://github.com/KIJEMORI/rust_GUI"
keywords = ["gui", "sdf", "wgpu", "3d", "graphics"]
categories = ["gui", "rendering", "graphics"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = "26.0.0"
image = "0.25"
winit = { version = "0.30.5", features = ["rwh_06"] }
android_logger = "0.14"
log = "0.4"
bytemuck = { version = "1.16", features = ["derive"] }
pollster = "0.3"
fontdue = "0.9.3"
rustc-hash = "2.1.0"
rayon = "1.10.0"
glam = { version = "0.29", features = ["bytemuck"] }
web-time = "1.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mimalloc = "0.1"

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "android")))'.dependencies]
arboard = "3.6.1"

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.30.5", features = ["rwh_06", "android-native-activity"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = ["Document", "Window", "Element", "HtmlCanvasElement"] }
console_error_panic_hook = "0.1.7" # Чтобы паники Rust красиво выводились в консоль браузера
console_log = "1.0.0"

[features]
default = ["3d_render"]
3d_render = []
